In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('train.csv')
df.shape

(404290, 6)

In [3]:
df.sample(5)

,id,qid1,qid2,question1,question2,is_duplicate
90514,90514,151872,32599,How come the media is quiet about Donald Trump...,Why isn't Donald Trump's rape case a bigger st...,1
218191,218191,17280,324723,Have you tried pokedates? Has it helped you fi...,"Monolinguals, have you ever tried to learn ano...",0
256556,256556,371698,371699,What is Bojack Horseman?,Is Bojack Horseman Overrated?,0
131901,131901,211350,211351,Do ghettos exist in Singapore?,Why do people from the suburbs act as if they’...,0
187953,187953,286329,286330,How one can check the jenuinness of sc/st cert...,Will I know if the person I blocked tries to c...,0

In [4]:
new_df = df.sample(30000)

In [5]:
new_df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [6]:
new_df.duplicated().sum()

np.int64(0)

In [7]:
ques_df = new_df[['question1','question2']]
ques_df.head()

,question1,question2
71270,How do I contact a real hacker?,How do l contact a hacker?
251152,What is the typical path to becoming a Hollywo...,What steps should someone follow to become a H...
249478,What is a music streaming service?,What music streaming services like Spotify are...
108651,Which is the best custom ROM I can install on ...,Which is the best custom ROM that I should ins...
377942,"Since the DNC and Clinton shafted Sanders, why...",Will Bernie Sanders supporters vote for the Li...

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
# merge texts
questions = list(ques_df['question1']) + list(ques_df['question2'])

cv = CountVectorizer(max_features=3000)
q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(),2)

In [9]:
temp_df1 = pd.DataFrame(q1_arr, index= ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index= ques_df.index)
temp_df = pd.concat([temp_df1, temp_df2], axis=1)
temp_df.shape

(30000, 6000)

In [10]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
71270,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
251152,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249478,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108651,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
377942,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67354,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
229048,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
306415,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
403372,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
234872,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
temp_df['is_duplicate'] = new_df['is_duplicate']

In [12]:
temp_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
71270,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
251152,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
249478,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108651,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
377942,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(temp_df.iloc[:,0:-1].values,temp_df.iloc[:,-1].values,test_size=0.2,random_state=1)

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7363333333333333

In [16]:
pip install xgboost

Collecting xgboost
  Using cached xgboost-3.4.1-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from xgboost) (2.5.1)
Requirement already satisfied: scipy in C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from xgboost) (1.17.1)
Downloading xgboost-3.4.1-py3-none-win_amd64.whl (48.9 MB)
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/48.9 MB 1.3 MB/s eta 0:00:37
    -------------------------------------- 0.8/48.9 MB 1,000.0 kB/s eta 0:00:49
    --------------------------------------- 1.0/48.9 MB 1.1 MB/s eta 0:00:44
   - -------------------------------------- 1.3/48.9 MB 1.1 MB/s eta 0:00:42
   - -------------------------------------- 1.3/48.9 MB 1.1 MB/s eta 0:00:42
   - -------------------------------------- 1.6/48.9 MB 1.0 MB/s eta 0:00:46
   - -------------------------------------- 1.8/48.9 MB 1.1 MB/s eta 0:00:44
   - -------------------------------------- 2.1/48.9 MB 1.1 MB/s eta 0:00:43
   - -------------------------------------- 2.4/48.9 MB 1.1 MB/s eta 0:00:41
   -- ------------------------------------- 2.6/48.9 MB 1.1 MB/s eta 0:00:41
   -- ------------------------------------- 2.9/48.9 MB 1.2 MB/s eta 0:00:40
   -- ------------------------------------- 3.1/48.9 MB 1.2 MB/s eta 0:00:40
   -- ------------------------------------- 3.1/48.9 MB 1.2 MB/s eta 0:00:40
   -- ------------------------------------- 3.4/48.9 MB 1.1 MB/s eta 0:00:44
   -- ------------------------------------- 3.7/48.9 MB 1.1 MB/s eta 0:00:42
   --- ------------------------------------ 3.9/48.9 MB 1.1 MB/s eta 0:00:41
   --- ------------------------------------ 4.2/48.9 MB 1.1 MB/s eta 0:00:41
   --- ------------------------------------ 4.2/48.9 MB 1.1 MB/s eta 0:00:41
   --- ------------------------------------ 4.7/48.9 MB 1.1 MB/s eta 0:00:41
   --- ------------------------------------ 4.7/48.9 MB 1.1 MB/s eta 0:00:41
   ---- ----------------------------------- 5.0/48.9 MB 1.1 MB/s eta 0:00:41
   ---- ----------------------------------- 5.5/48.9 MB 1.1 MB/s eta 0:00:40
   ---- ----------------------------------- 5.8/48.9 MB 1.1 MB/s eta 0:00:39
   ---- ----------------------------------- 6.0/48.9 MB 1.1 MB/s eta 0:00:39
   ----- ---------------------------------- 6.3/48.9 MB 1.1 MB/s eta 0:00:38
   ----- ---------------------------------- 6.6/48.9 MB 1.1 MB/s eta 0:00:38
   ----- ---------------------------------- 6.8/48.9 MB 1.1 MB/s eta 0:00:37
   ----- ---------------------------------- 7.1/48.9 MB 1.1 MB/s eta 0:00:37
   ----- ---------------------------------- 7.3/48.9 MB 1.1 MB/s eta 0:00:37
   ------ --------------------------------- 7.6/48.9 MB 1.2 MB/s eta 0:00:36
   ------ --------------------------------- 7.9/48.9 MB 1.2 MB/s eta 0:00:36
   ------ --------------------------------- 8.1/48.9 MB 1.2 MB/s eta 0:00:36
   ------ --------------------------------- 8.4/48.9 MB 1.2 MB/s eta 0:00:35
   ------- -------------------------------- 8.7/48.9 MB 1.2 MB/s eta 0:00:35
   ------- -------------------------------- 8.7/48.9 MB 1.2 MB/s eta 0:00:35
   ------- -------------------------------- 8.9/48.9 MB 1.1 MB/s eta 0:00:36
   ------- -------------------------------- 8.9/48.9 MB 1.1 MB/s eta 0:00:36
   ------- -------------------------------- 9.4/48.9 MB 1.1 MB/s eta 0:00:35
   ------- -------------------------------- 9.7/48.9 MB 1.1 MB/s eta 0:00:35
   ------- -------------------------------- 9.7/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.0/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.2/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.2/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.5/48.9 MB 1.1 MB/s eta 0:00:35
   -------- ------------------------------- 10.7/48.9 MB 828.2 kB/s eta 0:00:47
   -------- ------------------------------- 10.7/48.9 MB 828.2 kB/s eta 0:00:47
   -------- ------------------------------- 10.7/48.9 MB 828.2 kB/s eta 0:00:47
   -------- ------------------------------- 10.7/48.9 MB 828.2 kB/s eta 0:00:47
   -------- ------------------------------- 10.7/48.9 MB 828.2 kB/s eta 0:00:47
   -------- ------------------------------- 10.7/48.9 MB 828.2 kB/s eta 0:00:47
   -------- ------------------------------- 10.7/48.9 MB 828.2 kB/s eta 0:00:47
   -------- ------------------------------- 10.7/48.9 MB 828.2 kB/s eta 0:00:47
   -------- ------------------------------- 10.7/48.9 MB 828.2 kB/s eta 0:00:47
   -------- ------------------------------- 10.7/48.9 MB 828.2 kB/s eta 0:00:47
   -------- ------------------------------- 10.7/48.9 MB 828.2 kB/s eta 0:00:47
   -------- ------------------------------- 10.7/48.9 MB 828.2 kB/s eta 0:00:47
   -------- ------------------------------- 10.7/48.9 MB 828.2 kB/s eta 0:00:47
   -------- ------------------------------- 10.7/48.9 MB 828.2 kB/s eta 0:00:47
   -------- ------------------------------- 10.7/48.9 MB 828.2 kB/s eta 0:00:47
   -------- ------------------------------- 11.0/48.9 MB 674.0 kB/s eta 0:00:57
   --------- ------------------------------ 11.3/48.9 MB 683.5 kB/s eta 0:00:56
   --------- ------------------------------ 11.3/48.9 MB 683.5 kB/s eta 0:00:56
   --------- ------------------------------ 11.5/48.9 MB 682.9 kB/s eta 0:00:55
   --------- ------------------------------ 11.8/48.9 MB 691.1 kB/s eta 0:00:54
   --------- ------------------------------ 12.1/48.9 MB 698.6 kB/s eta 0:00:53
   ---------- ----------------------------- 12.3/48.9 MB 705.6 kB/s eta 0:00:52
   ---------- ----------------------------- 12.3/48.9 MB 705.6 kB/s eta 0:00:52
   ---------- ----------------------------- 12.6/48.9 MB 706.7 kB/s eta 0:00:52
   ---------- ----------------------------- 12.8/48.9 MB 710.1 kB/s eta 0:00:51
   ---------- ----------------------------- 12.8/48.9 MB 710.1 kB/s eta 0:00:51
   ---------- ----------------------------- 13.1/48.9 MB 712.2 kB/s eta 0:00:51
   ---------- ----------------------------- 13.1/48.9 MB 712.2 kB/s eta 0:00:51
   ---------- ----------------------------- 13.1/48.9 MB 712.2 kB/s eta 0:00:51
   ---------- ----------------------------- 13.1/48.9 MB 712.2 kB/s eta 0:00:51
   ---------- ----------------------------- 13.1/48.9 MB 712.2 kB/s eta 0:00:51
   ---------- ----------------------------- 13.1/48.9 MB 712.2 kB/s eta 0:00:51
   ---------- ----------------------------- 13.1/48.9 MB 712.2 kB/s eta 0:00:51
   ---------- ----------------------------- 13.1/48.9 MB 712.2 kB/s eta 0:00:51
   ---------- ----------------------------- 13.1/48.9 MB 712.2 kB/s eta 0:00:51
   ---------- ----------------------------- 13.4/48.9 MB 652.3 kB/s eta 0:00:55
   ---------- ----------------------------- 13.4/48.9 MB 652.3 kB/s eta 0:00:55
   ---------- ----------------------------- 13.4/48.9 MB 652.3 kB/s eta 0:00:55
   ---------- ----------------------------- 13.4/48.9 MB 652.3 kB/s eta 0:00:55
   ---------- ----------------------------- 13.4/48.9 MB 652.3 kB/s eta 0:00:55
   ---------- ----------------------------- 13.4/48.9 MB 652.3 kB/s eta 0:00:55
   ---------- ----------------------------- 13.4/48.9 MB 652.3 kB/s eta 0:00:55
   ---------- ----------------------------- 13.4/48.9 MB 652.3 kB/s eta 0:00:55
   ---------- ----------------------------- 13.4/48.9 MB 652.3 kB/s eta 0:00:55
   ---------- ----------------------------- 13.4/48.9 MB 652.3 kB/s eta 0:00:55
   ----------- ---------------------------- 13.6/48.9 MB 602.1 kB/s eta 0:00:59
   ----------- ---------------------------- 13.6/48.9 MB 602.1 kB/s eta 0:00:59
   ----------- ---------------------------- 14.2/48.9 MB 613.8 kB/s eta 0:00:57
   ----------- ---------------------------- 14.4/48.9 MB 619.9 kB/s eta 0:00:56
   ----------- ---------------------------- 14.7/48.9 MB 625.3 kB/s eta 0:00:55
   ------------ --------------------------- 14.9/48.9 MB 631.5 kB/s eta 0:00:54
   ------------ --------------------------- 15.2/48.9 MB 637.1 kB/s eta 0:00:53
   ------------ --------------------------- 15.2/48.9 MB 637.1 kB/s eta 0:00:53
   ------------ --------------------------- 15.5/48.9 MB 641.8 kB/s eta 0:00:53
   ------------- -------------------------- 16.0/48.9 MB 653.2 kB/s eta 0:00:51
   ------------- -------------------------- 16.0/48.9 MB 653.2 kB/s eta 0:00:51
   ------------- -------------------------- 16.3/48.9 MB 657.9 kB/s eta 0:00:50
   ------------- -------------------------- 16.3/48.9 MB 657.9 kB/s eta 0:00:50
   ------------- -------------------------- 16.3/48.9 MB 657.9 kB/s eta 0:00:50
   ------------- -------------------------- 16.3/48.9 MB 657.9 kB/s eta 0:00:50
   ------------- -------------------------- 16.3/48.9 MB 657.9 kB/s eta 0:00:50
   ------------- -------------------------- 16.3/48.9 MB 657.9 kB/s eta 0:00:50
   ------------- -------------------------- 16.3/48.9 MB 657.9 kB/s eta 0:00:50
   ------------- -------------------------- 16.3/48.9 MB 657.9 kB/s eta 0:00:50
   ------------- -------------------------- 16.8/48.9 MB 632.7 kB/s eta 0:00:51
   ------------- -------------------------- 17.0/48.9 MB 637.7 kB/s eta 0:00:51
   ------------- -------------------------- 17.0/48.9 MB 637.7 kB/s eta 0:00:51
   -------------- ------------------------- 17.3/48.9 MB 637.8 kB/s eta 0:00:50
   -------------- ------------------------- 17.3/48.9 MB 637.8 kB/s eta 0:00:50
   -------------- ------------------------- 17.8/48.9 MB 646.7 kB/s eta 0:00:49
   -------------- ------------------------- 18.1/48.9 MB 651.6 kB/s eta 0:00:48
   -------------- ------------------------- 18.4/48.9 MB 656.3 kB/s eta 0:00:47
   -------------- ------------------------- 18.4/48.9 MB 656.3 kB/s eta 0:00:47
   --------------- ------------------------ 18.6/48.9 MB 658.2 kB/s eta 0:00:47
   --------------- ------------------------ 18.9/48.9 MB 660.1 kB/s eta 0:00:46
   --------------- ------------------------ 18.9/48.9 MB 660.1 kB/s eta 0:00:46
   --------------- ------------------------ 19.1/48.9 MB 660.6 kB/s eta 0:00:46
   --------------- ------------------------ 19.4/48.9 MB 666.3 kB/s eta 0:00:45
   ---------------- ----------------------- 19.7/48.9 MB 670.8 kB/s eta 0:00:44
   ---------------- ----------------------- 19.9/48.9 MB 672.5 kB/s eta 0:00:44
   ---------------- ----------------------- 20.2/48.9 MB 676.8 kB/s eta 0:00:43
   ---------------- ----------------------- 20.4/48.9 MB 680.7 kB/s eta 0:00:42
   ---------------- ----------------------- 20.7/48.9 MB 684.9 kB/s eta 0:00:42
   ----------------- ---------------------- 21.0/48.9 MB 684.5 kB/s eta 0:00:41
   ----------------- ---------------------- 21.2/48.9 MB 687.4 kB/s eta 0:00:41
   ----------------- ---------------------- 21.5/48.9 MB 691.4 kB/s eta 0:00:40
   ----------------- ---------------------- 21.8/48.9 MB 691.2 kB/s eta 0:00:40
   ----------------- ---------------------- 22.0/48.9 MB 691.1 kB/s eta 0:00:39
   ------------------ --------------------- 22.3/48.9 MB 694.1 kB/s eta 0:00:39
   ------------------ --------------------- 22.5/48.9 MB 693.7 kB/s eta 0:00:39
   ------------------ --------------------- 22.8/48.9 MB 694.4 kB/s eta 0:00:38
   ------------------ --------------------- 23.1/48.9 MB 693.5 kB/s eta 0:00:38
   ------------------- -------------------- 23.3/48.9 MB 693.9 kB/s eta 0:00:37
   ------------------- -------------------- 23.6/48.9 MB 693.8 kB/s eta 0:00:37
   ------------------- -------------------- 23.9/48.9 MB 693.7 kB/s eta 0:00:37
   ------------------- -------------------- 23.9/48.9 MB 693.7 kB/s eta 0:00:37
   ------------------- -------------------- 24.1/48.9 MB 698.7 kB/s eta 0:00:36
   ------------------- -------------------- 24.1/48.9 MB 698.7 kB/s eta 0:00:36
   ------------------- -------------------- 24.4/48.9 MB 686.2 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.6/48.9 MB 686.6 kB/s eta 0:00:36
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 24.9/48.9 MB 539.1 kB/s eta 0:00:45
   -------------------- ------------------- 25.2/48.9 MB 485.2 kB/s eta 0:00:50
   -------------------- ------------------- 25.4/48.9 MB 490.9 kB/s eta 0:00:48
   -------------------- ------------------- 25.7/48.9 MB 547.1 kB/s eta 0:00:43
   --------------------- ------------------ 26.0/48.9 MB 552.8 kB/s eta 0:00:42
   --------------------- ------------------ 26.0/48.9 MB 552.8 kB/s eta 0:00:42
   --------------------- ------------------ 26.2/48.9 MB 554.2 kB/s eta 0:00:42
   --------------------- ------------------ 26.5/48.9 MB 557.2 kB/s eta 0:00:41
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40
   --------------------- ------------------ 26.7/48.9 MB 562.5 kB/s eta 0:00:40

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: C:\Users\USER\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [17]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(X_test)
accuracy_score(y_test,y_pred)

0.7288333333333333